### ISSUE TITLE
Konfiguration with laravel 6

### ISSUE THREAD

**Issue by richardklings** [ziffmedia/laravel-onelogin#2]
I am trying to use the package with laravel 6. 

I used the following steps. 

composer create-project --prefer-dist laravel/laravel blog "6.0.*"

composer require ziffmedia/laravel-onelogin

php artisan vendor:publish --provider='ZiffMedia\Laravel\Onelogin\OneloginServiceProvider'
Unable to locate publishable resources.
Publishing complete.

When I use the project blog in version "5.7" everything works fine. 

Are there any experiences with newer laravel versions. 

We want to update to 7. Therefore I am not sure if I can use this package.

**Comment by ralphschindler** [comment]
Sounds like you're on the command line and need to escape that provider name, and/or use the interactive `vendor:publish`.
