### ISSUE TITLE
PHP 8 Compatability

### ISSUE THREAD

**Issue by adammparker** [ziffmedia/laravel-onelogin#3]
Looks like the underlying package has been updated by several minor versions, including one that supports PHP 8. Any chance we could cut a new release here so we can use this package in a PHP 8 Laravel app?

**Comment by ralphschindler** [comment]
Sorry, just seeing this. I'm pretty sure it just works no? I am using it in php8 projects, though I will check again.

**Comment by adammparker** [comment]
We ended up not needing OneLogin in this particular app, thanks for following up though!
